// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truckload.Ebs.Data;

#nullable disable

namespace Truckload.Ebs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Truckload.Ebs.Entities.Channel", b =>
            {
                b.Property<string>("ChannelId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("IngestKey")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("ChannelId");

                b.HasIndex("IngestKey")
                    .IsUnique();

                b.ToTable("Channels");
            });

            modelBuilder.Entity("Truckload.Ebs.Entities.TelemetrySnapshot", b =>
            {
                b.Property<string>("ChannelId")
                    .HasColumnType("text");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("ChannelId");

                b.ToTable("TelemetrySnapshots");
            });

            modelBuilder.Entity("Truckload.Ebs.Entities.TelemetrySnapshot", b =>
            {
                b.HasOne("Truckload.Ebs.Entities.Channel", "Channel")
                    .WithOne("LatestTelemetry")
                    .HasForeignKey("Truckload.Ebs.Entities.TelemetrySnapshot", "ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Channel");
            });

            modelBuilder.Entity("Truckload.Ebs.Entities.Channel", b =>
            {
                b.Navigation("LatestTelemetry");
            });
#pragma warning restore 612, 618
        }
    }
}
