// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Truckload.Ebs.Data;

#nullable disable

namespace Truckload.Ebs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930013345_SyncModelSnapshot")]
    partial class SyncModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Truckload.Ebs.Entities.Channel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IngestKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChannelId");

                    b.HasIndex("IngestKey")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Truckload.Ebs.Entities.JobHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "CompletedAt");

                    b.ToTable("JobHistoryEntries");
                });

            modelBuilder.Entity("Truckload.Ebs.Entities.TelemetrySnapshot", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChannelId");

                    b.ToTable("TelemetrySnapshots");
                });

            modelBuilder.Entity("Truckload.Ebs.Entities.JobHistoryEntry", b =>
                {
                    b.HasOne("Truckload.Ebs.Entities.Channel", "Channel")
                        .WithMany("JobHistory")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Truckload.Ebs.Entities.TelemetrySnapshot", b =>
                {
                    b.HasOne("Truckload.Ebs.Entities.Channel", "Channel")
                        .WithOne("LatestTelemetry")
                        .HasForeignKey("Truckload.Ebs.Entities.TelemetrySnapshot", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Truckload.Ebs.Entities.Channel", b =>
                {
                    b.Navigation("JobHistory");

                    b.Navigation("LatestTelemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
